[build]
  publish = "_site"
  command = "npm run build"

[[redirects]]
  from = "https://zaccolley.com/*"
  to = "https://zac.land/:splat"
  
[[redirects]]
  from = "https://zaccolley.com"
  to = "https://zac.land"

[[redirects]]
  from = "https://zaccolley.netlify.com/*"
  to = "https://zac.land/:splat"
  
[[redirects]]
  from = "https://zaccolley.netlify.com"
  to = "https://zac.land"

[[redirects]]
 from = "/momanddad"
 to = "https://lynneandpaul.surge.sh"

[[redirects]]
  from = "/minecraftexplore/*"
  to = "https://zacs-stuff.netlify.com/minecraftexplore/:splat"

[[redirects]]
  from = "/stuff/*"
  to = "https://zacs-stuff.netlify.com/:splat"
