[build]
  publish = "_site"
  command = "npm run build"

[[redirects]]
 from = "/momanddad"
 to = "https://lynneandpaul.surge.sh"

[[redirects]]
  from = "/minecraftexplore/*"
  to = "https://zacs-stuff.netlify.com/minecraftexplore/:splat"

[[redirects]]
  from = "/stuff/*"
  to = "https://zacs-stuff.netlify.com/:splat"
